<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Interacción con API</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            text-align: center;
            margin-top: 50px;
        }
        input, button {
            margin: 10px;
            padding: 10px;
            font-size: 16px;
        }
    </style>
</head>
<body>
    <h1>Interactúa con la API</h1>
    <form id="api-form">
        <input type="text" id="user-input" placeholder="Escribe algo" required />
        <button type="submit">Enviar</button>
    </form>
    <h3>Respuesta:</h3>
    <pre id="response"></pre>

    <script>
        const form = document.getElementById('api-form');
        const responseElement = document.getElementById('response');

        form.addEventListener('submit', async (event) => {
            event.preventDefault(); // Evitar recargar la página
            const userInput = document.getElementById('user-input').value;

            // Enviar datos a la API
            const response = await fetch('https://railway-production-a260.up.railway.app/insuficiencia', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({ mensaje: userInput })
            });

            // Manejar la respuesta
            const data = await response.json();
            responseElement.textContent = JSON.stringify(data, null, 2);
        });
    </script>
</body>
</html>
